/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EveButton {
        /**
          * Set to `"outline"` for a transparent button with a border, or to `"solid"`. The default style is `"solid"`.
         */
        "fill"?: "outline" | "solid";
        /**
          * Contains a URL or a URL fragment that the hyperlink points to.
         */
        "href": string | undefined;
        /**
          * Specifies the relationship of the target object to the link object. The value is a space-separated list of [link types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).
         */
        "rel": string | undefined;
        /**
          * Specifies where to display the linked URL. Special keywords: `"_blank"`, `"_self"`, `"_parent"`, `"_top"`.
         */
        "target": string | undefined;
    }
    interface EveIntroduction {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface EveStringify {
        "data": string | Array<Object> | Object;
    }
}
declare global {
    interface HTMLEveButtonElement extends Components.EveButton, HTMLStencilElement {
    }
    var HTMLEveButtonElement: {
        prototype: HTMLEveButtonElement;
        new (): HTMLEveButtonElement;
    };
    interface HTMLEveIntroductionElement extends Components.EveIntroduction, HTMLStencilElement {
    }
    var HTMLEveIntroductionElement: {
        prototype: HTMLEveIntroductionElement;
        new (): HTMLEveIntroductionElement;
    };
    interface HTMLEveStringifyElement extends Components.EveStringify, HTMLStencilElement {
    }
    var HTMLEveStringifyElement: {
        prototype: HTMLEveStringifyElement;
        new (): HTMLEveStringifyElement;
    };
    interface HTMLElementTagNameMap {
        "eve-button": HTMLEveButtonElement;
        "eve-introduction": HTMLEveIntroductionElement;
        "eve-stringify": HTMLEveStringifyElement;
    }
}
declare namespace LocalJSX {
    interface EveButton {
        /**
          * Set to `"outline"` for a transparent button with a border, or to `"solid"`. The default style is `"solid"`.
         */
        "fill"?: "outline" | "solid";
        /**
          * Contains a URL or a URL fragment that the hyperlink points to.
         */
        "href"?: string | undefined;
        /**
          * Specifies the relationship of the target object to the link object. The value is a space-separated list of [link types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).
         */
        "rel"?: string | undefined;
        /**
          * Specifies where to display the linked URL. Special keywords: `"_blank"`, `"_self"`, `"_parent"`, `"_top"`.
         */
        "target"?: string | undefined;
    }
    interface EveIntroduction {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface EveStringify {
        "data"?: string | Array<Object> | Object;
    }
    interface IntrinsicElements {
        "eve-button": EveButton;
        "eve-introduction": EveIntroduction;
        "eve-stringify": EveStringify;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eve-button": LocalJSX.EveButton & JSXBase.HTMLAttributes<HTMLEveButtonElement>;
            "eve-introduction": LocalJSX.EveIntroduction & JSXBase.HTMLAttributes<HTMLEveIntroductionElement>;
            "eve-stringify": LocalJSX.EveStringify & JSXBase.HTMLAttributes<HTMLEveStringifyElement>;
        }
    }
}
